const translations = {
    en: {
        "nav.practice": "Practice Areas",
        "nav.team": "Team",
        "nav.about": "About",
        "nav.contact": "Contact",
        "nav.consult": "Consultation",
        "hero.badge": "Trusted Legal Partners",
        "hero.title": "Leading Legal Solutions <br/>in <span class=\"hero-accent text-accent\">Uzbekistan</span>",
        "hero.body": "Expert counsel for complex corporate, IP, and litigation matters. We navigate the legal landscape so you can focus on growth.",
        "hero.cta.primary": "Request Consultation",
        "hero.cta.secondary": "Our Practice Areas",
        "why.title": "Why Choose All-Legal",
        "why.body": "We combine local expertise with international standards to deliver exceptional results for our clients.",
        "why.cards.one.title": "Deep Experience",
        "why.cards.one.body": "Over 20 years of combined legal expertise navigating both local regulations and international law frameworks.",
        "why.cards.two.title": "Unwavering Reliability",
        "why.cards.two.body": "Trusted by top Fortune 500 companies operating in Central Asia for our consistency and ethical standards.",
        "why.cards.three.title": "Individual Approach",
        "why.cards.three.body": "We don't believe in templates. Every strategy is tailored specifically to meet your unique business goals.",
        "about.established": "Established 2022",
        "about.tagline": "Delivering excellence in Uzbek law",
        "about.eyebrow": "About the Firm",
        "about.title": "Protecting Your Rights & Interests in Uzbekistan",
        "about.p1": "Founded in 2022, All-Legal specializes in safeguarding the legal rights of both corporate entities and individuals within the Republic of Uzbekistan. We are dedicated to providing clear, actionable counsel in a rapidly evolving legal landscape.",
        "about.p2": "Our firm serves as a vital bridge for foreign investment, offering comprehensive support in <span class=\"text-navy dark:text-white font-semibold\">corporate law, tax planning, contract negotiation, and migration issues</span>. We expertly manage the complexities of license acquisition, visas, and work permits, ensuring smooth operations for international clients.",
        "about.p3": "Our team of <span class=\"text-navy dark:text-white font-semibold\">7 qualified lawyers</span> brings deep expertise to every case. We are proud of our successful history assisting over <span class=\"text-navy dark:text-white font-semibold\">70 legal entities</span> across key sectors including construction, tourism, trade, IT, and finance.",
        "about.stats.entities": "Legal Entities Served",
        "about.stats.sectors": "Key Sectors",
        "about.stats.lawyers": "Qualified Lawyers",
        "practice.eyebrow": "Expertise",
        "practice.title": "Practice Areas",
        "practice.viewAll": "View all practices",
        "practice.learnMore": "Learn more",
        "practice.cards.one.title": "Contract Drafting & Review",
        "practice.cards.one.body": "Drafting, analyzing, and conducting legal expert review of contracts.",
        "practice.cards.two.title": "Employment Documentation",
        "practice.cards.two.body": "Preparing employment contracts and other labor-related regulatory documents.",
        "practice.cards.three.title": "Labor Law Advice",
        "practice.cards.three.body": "Providing legal advice on labor law matters.",
        "practice.cards.four.title": "Legal Consulting",
        "practice.cards.four.body": "Providing consulting services on legal matters.",
        "practice.cards.five.title": "Company Registration",
        "practice.cards.five.body": "Registering companies and preparing founding documents.",
        "practice.cards.six.title": "Contract Dispute Resolution",
        "practice.cards.six.body": "Resolving contract disputes and providing legal support in court proceedings.",
        "practice.cards.seven.title": "Court Representation",
        "practice.cards.seven.body": "Protecting citizens' rights in courts for civil, economic, labor, and administrative cases.",
        "practice.cards.eight.title": "Foreign Nationals Support",
        "practice.cards.eight.body": "Protecting foreign nationals' rights in Uzbekistan and providing legal services to obtain entry permits.",
        "trusted.title": "Recognized by leading international directories",
        "team.title": "Our Team",
        "team.viewProfile": "View Profile",
        "team.roles.one": "Managing Partner",
        "team.roles.two": "Partner, Corporate Law",
        "team.roles.three": "Partner, Litigation",
        "team.roles.four": "Head of Tax Practice",
        "cta.eyebrow": "Let's Discuss Your Case",
        "cta.title": "Ready to Protect Your Interests?",
        "cta.body": "Schedule a confidential consultation with our experts. We will respond within 24 hours.",
        "cta.contact.office": "Office",
      "cta.contact.address":
        "Toshkent shahri, Yunusobod tumani Minor MFY.Markaz-6 mavzesi, 111-uy, 25-xona",
      "cta.contact.phone": "Phone",
      "cta.contact.phoneValue": "+998 88 488 0203",
      "cta.contact.phoneValue2": "+998 90 719 22 23",
      "cta.contact.email": "Email",
      "cta.contact.emailValue": "info@allegal.uz",
      "cta.contact.telegram": "Telegram",
      "cta.contact.telegramValue": "@umarjon_jumaniyazov",
      "cta.contact.instagram": "Instagram",
      "cta.contact.instagramValue": "instagram.com/all_legal.uz",
      "cta.contact.hours": "Hours",
      "cta.contact.hours.mon": "Mon: 9:00–18:00",
      "cta.contact.hours.tue": "Tue: 9:00–18:00",
      "cta.contact.hours.wed": "Wed: 9:00–18:00",
      "cta.contact.hours.thu": "Thu: 9:00–18:00",
      "cta.contact.hours.fri": "Fri: 9:00–18:00",
      "cta.contact.hours.sat": "Sat: Closed",
      "cta.contact.hours.sun": "Sun: Closed",
        "form.name": "Name",
        "form.name.placeholder": "Full Name",
        "form.phone": "Phone",
        "form.phone.placeholder": "+998",
        "form.email": "Email",
        "form.email.placeholder": "example@company.com",
        "form.message": "Message",
        "form.message.placeholder": "Briefly describe your legal matter...",
        "form.submit": "Submit Request",
        "footer.blurb": "All-Legal provides top-tier legal services tailored to the complex needs of modern businesses in Uzbekistan and Central Asia.",
        "footer.firm.title": "Firm",
        "footer.firm.about": "About Us",
        "footer.firm.team": "Our Team",
        "footer.firm.practice": "Practice Areas",
        "footer.firm.contact": "Contact",
        "footer.firm.email": "Email",
        "footer.firm.phone": "Phone",
        "footer.firm.instagram": "Instagram",
        "footer.firm.telegram": "Telegram",
        "footer.services.title": "Services",
        "footer.services.corporate": "Corporate",
        "footer.services.litigation": "Litigation",
        "footer.services.realestate": "Real Estate",
        "footer.services.tax": "Tax Law",
        "footer.connect.title": "Connect",
        "footer.copyright": "© 2026 All-Legal Law Firm. All rights reserved.",
        "footer.legal.privacy": "Privacy Policy",
        "footer.legal.terms": "Terms of Use"
    },
    ru: {
        "nav.practice": "Практики",
        "nav.team": "Команда",
        "nav.about": "О нас",
        "nav.contact": "Контакты",
        "nav.consult": "Консультация",
        "hero.badge": "Надежные юридические партнеры",
        "hero.title": "Ведущие юридические решения <br/>в <span class=\"hero-accent text-accent\">Узбекистане</span>",
        "hero.body": "Экспертное сопровождение сложных корпоративных, IP и судебных вопросов. Мы ведем ваш юридический процесс, чтобы вы могли сосредоточиться на росте.",
        "hero.cta.primary": "Запросить консультацию",
        "hero.cta.secondary": "Наши практики",
        "why.title": "Почему выбирают All-Legal",
        "why.body": "Мы объединяем местную экспертизу с международными стандартами, чтобы обеспечивать исключительные результаты для клиентов.",
        "why.cards.one.title": "Глубокий опыт",
        "why.cards.one.body": "Более 20 лет совокупного юридического опыта в области местного регулирования и международного права.",
        "why.cards.two.title": "Непоколебимая надежность",
        "why.cards.two.body": "Нам доверяют ведущие компании Fortune 500 в Центральной Азии за стабильность и этические стандарты.",
        "why.cards.three.title": "Индивидуальный подход",
        "why.cards.three.body": "Мы не верим в шаблоны. Каждая стратегия подбирается под ваши уникальные цели бизнеса.",
        "about.established": "Основана в 2022",
        "about.tagline": "Совершенство в узбекском праве",
        "about.eyebrow": "О фирме",
        "about.title": "Защищаем ваши права и интересы в Узбекистане",
        "about.p1": "Основанная в 2022 году, All-Legal специализируется на защите прав как корпоративных клиентов, так и частных лиц в Республике Узбекистан. Мы предоставляем четкие и практичные рекомендации в условиях быстро меняющегося правового поля.",
        "about.p2": "Наша фирма является надежным мостом для иностранных инвестиций и обеспечивает поддержку в <span class=\"text-navy dark:text-white font-semibold\">корпоративном праве, налоговом планировании, переговорах по контрактам и миграционных вопросах</span>. Мы профессионально ведем вопросы лицензий, виз и разрешений на работу, обеспечивая бесперебойную работу международных клиентов.",
        "about.p3": "Наша команда из <span class=\"text-navy dark:text-white font-semibold\">7 квалифицированных юристов</span> обладает глубокой экспертизой. Мы гордимся успешной работой с более чем <span class=\"text-navy dark:text-white font-semibold\">70 юридическими лицами</span> в ключевых секторах — строительство, туризм, торговля, IT и финансы.",
        "about.stats.entities": "Юридических лиц обслужено",
        "about.stats.sectors": "Ключевых отраслей",
        "about.stats.lawyers": "Квалифицированных юристов",
        "practice.eyebrow": "Экспертиза",
        "practice.title": "Практики",
        "practice.viewAll": "Все практики",
        "practice.learnMore": "Подробнее",
        "practice.cards.one.title": "Экспертиза договоров",
        "practice.cards.one.body": "Разработка, анализ и проведение юридической экспертизы договоров.",
        "practice.cards.two.title": "Трудовая документация",
        "practice.cards.two.body": "Подготовка трудовых договоров и иных нормативных документов по трудовому праву.",
        "practice.cards.three.title": "Консультации по трудовому праву",
        "practice.cards.three.body": "Предоставление юридических консультаций по вопросам трудового законодательства.",
        "practice.cards.four.title": "Юридический консалтинг",
        "practice.cards.four.body": "Оказание консультационных услуг по юридическим вопросам.",
        "practice.cards.five.title": "Регистрация компаний",
        "practice.cards.five.body": "Регистрация компаний и подготовка учредительных документов.",
        "practice.cards.six.title": "Договорные споры",
        "practice.cards.six.body": "Разрешение договорных споров и юридическое сопровождение в судебных процессах.",
        "practice.cards.seven.title": "Судебная защита",
        "practice.cards.seven.body": "Защита прав граждан в судах по гражданским, экономическим, трудовым и административным делам.",
        "practice.cards.eight.title": "Поддержка иностранных граждан",
        "practice.cards.eight.body": "Защита прав иностранных граждан в Узбекистане и юридические услуги по получению разрешения на въезд в Узбекистан.",
        "trusted.title": "Признаны ведущими международными справочниками",
        "team.title": "Наша команда",
        "team.viewProfile": "Смотреть профиль",
        "team.roles.one": "Управляющий партнер",
        "team.roles.two": "Партнер, корпоративное право",
        "team.roles.three": "Партнер, судебные споры",
        "team.roles.four": "Руководитель налоговой практики",
        "cta.eyebrow": "Обсудим ваше дело",
        "cta.title": "Готовы защитить ваши интересы?",
        "cta.body": "Запишитесь на конфиденциальную консультацию с нашими экспертами. Мы ответим в течение 24 часов.",
        "cta.contact.office": "Офис",
      "cta.contact.address":
        "г. Ташкент, Юнусабадский р-н, МФЙ Минор, массив Марказ-6, дом 111, кв. 25",
      "cta.contact.phone": "Телефон",
      "cta.contact.phoneValue": "+998 88 488 0203",
      "cta.contact.phoneValue2": "+998 90 719 22 23",
      "cta.contact.email": "Email",
      "cta.contact.emailValue": "info@allegal.uz",
      "cta.contact.telegram": "Telegram",
      "cta.contact.telegramValue": "@umarjon_jumaniyazov",
      "cta.contact.instagram": "Instagram",
      "cta.contact.instagramValue": "instagram.com/all_legal.uz",
      "cta.contact.hours": "График",
      "cta.contact.hours.mon": "Пн: 9:00–18:00",
      "cta.contact.hours.tue": "Вт: 9:00–18:00",
      "cta.contact.hours.wed": "Ср: 9:00–18:00",
      "cta.contact.hours.thu": "Чт: 9:00–18:00",
      "cta.contact.hours.fri": "Пт: 9:00–18:00",
      "cta.contact.hours.sat": "Сб: выходной",
      "cta.contact.hours.sun": "Вс: выходной",
        "form.name": "Имя",
        "form.name.placeholder": "Полное имя",
        "form.phone": "Телефон",
        "form.phone.placeholder": "+998",
        "form.email": "Email",
        "form.email.placeholder": "example@company.com",
        "form.message": "Сообщение",
        "form.message.placeholder": "Кратко опишите ваш юридический вопрос...",
        "form.submit": "Отправить запрос",
        "footer.blurb": "All-Legal предоставляет первоклассные юридические услуги для современных компаний в Узбекистане и Центральной Азии.",
        "footer.firm.title": "Фирма",
        "footer.firm.about": "О нас",
        "footer.firm.team": "Наша команда",
        "footer.firm.practice": "Услуги",
        "footer.firm.contact": "Контакты",
        "footer.firm.email": "Электронная почта",
        "footer.firm.phone": "Телефон",
        "footer.firm.instagram": "Инстаграм",
        "footer.firm.telegram": "Tелеграм",
        "footer.services.title": "Услуги",
        "footer.services.corporate": "Корпоративное право",
        "footer.services.litigation": "Судебные споры",
        "footer.services.realestate": "Недвижимость",
        "footer.services.tax": "Налоговое право",
        "footer.connect.title": "Связаться",
        "footer.copyright": "© 2026 Юридическая фирма All-Legal. Все права защищены.",
        "footer.legal.privacy": "Политика конфиденциальности",
        "footer.legal.terms": "Условия использования"
    },
    uz: {
        "nav.practice": "Yo'nalishlar",
        "nav.team": "Jamoa",
        "nav.about": "Biz haqimizda",
        "nav.contact": "Aloqa",
        "nav.consult": "Maslahat",
        "hero.badge": "Ishonchli yuridik hamkorlar",
        "hero.title": "O'zbekistonda <br/><span class=\"hero-accent text-accent\">yetakchi yuridik yechimlar</span>",
        "hero.body": "Murakkab korporativ, intellektual mulk va sud masalalarida ekspert yordami. Biz yuridik jarayonlarni boshqaramiz, siz esa o'sishga e'tibor qaratasiz.",
        "hero.cta.primary": "Maslahat so'rash",
        "hero.cta.secondary": "Yo'nalishlarimiz",
        "why.title": "Nega All-Legal",
        "why.body": "Biz mahalliy tajribani xalqaro standartlar bilan uyg'unlashtirib, mijozlar uchun yuqori natijalarni taqdim etamiz.",
        "why.cards.one.title": "Chuqur tajriba",
        "why.cards.one.body": "Mahalliy tartiblar va xalqaro huquq bo'yicha 20 yildan ortiq jamlangan tajriba.",
        "why.cards.two.title": "Barqaror ishonchlilik",
        "why.cards.two.body": "Markaziy Osiyoda faoliyat yuritayotgan Fortune 500 kompaniyalari bizni barqarorlik va yuqori axloqiy me'yorlar uchun tanlaydi.",
        "why.cards.three.title": "Individual yondashuv",
        "why.cards.three.body": "Biz shablonlarga ishonmaymiz. Har bir strategiya sizning biznes maqsadlaringizga mos yaratiladi.",
        "about.established": "2022 yilda tashkil etilgan",
        "about.tagline": "O'zbek huquqida mukammallik",
        "about.eyebrow": "Firma haqida",
        "about.title": "O'zbekistonda huquq va manfaatlaringizni himoya qilamiz",
        "about.p1": "2022 yilda tashkil etilgan All-Legal O'zbekiston Respublikasida yuridik shaxslar va jismoniy shaxslar huquqlarini himoya qilishga ixtisoslashgan. Biz tez o'zgarayotgan huquqiy muhitda aniq va amaliy maslahatlar taqdim etamiz.",
        "about.p2": "Firmamiz xorijiy investitsiyalar uchun ishonchli ko'prik bo'lib, <span class=\"text-navy dark:text-white font-semibold\">korporativ huquq, soliq rejalashtirish, shartnoma muzokaralari va migratsiya masalalari</span> bo'yicha to'liq ko'mak ko'rsatadi. Biz litsenziyalar, vizalar va mehnat ruxsatnomalari bo'yicha murakkab jarayonlarni boshqarib, xalqaro mijozlar uchun barqaror ishlashni ta'minlaymiz.",
        "about.p3": "Bizning <span class=\"text-navy dark:text-white font-semibold\">7 nafar malakali yuristdan</span> iborat jamoamiz har bir ishga chuqur tajriba bilan yondashadi. Biz qurilish, turizm, savdo, IT va moliya kabi sohalarda <span class=\"text-navy dark:text-white font-semibold\">70 dan ortiq yuridik shaxsga</span> muvaffaqiyatli yordam berganimizdan faxrlanamiz.",
        "about.stats.entities": "Yuridik shaxslar",
        "about.stats.sectors": "Asosiy sohalar",
        "about.stats.lawyers": "Malakali yuristlar",
        "practice.eyebrow": "Ekspertiza",
        "practice.title": "Xizmat yo'nalishlari",
        "practice.viewAll": "Barcha yo'nalishlar",
        "practice.learnMore": "Batafsil",
        "practice.cards.one.title": "Shartnoma ekspertizasi",
        "practice.cards.one.body": "Shartnomalarni ishlab chiqish, tahlil qilish va huquqiy ekspertizadan o‘tkazish",
        "practice.cards.two.title": "Mehnat hujjatlari",
        "practice.cards.two.body": "Mehnat shartnomalari hamda mehnatga doir boshqa me’yoriy hujjatlarni tayyorlash",
        "practice.cards.three.title": "Mehnat huquqi bo‘yicha maslahat",
        "practice.cards.three.body": "Mehnat qonunchiligi masalalari bo‘yicha huquqiy maslahatlar berish",
        "practice.cards.four.title": "Yuridik konsultatsiya",
        "practice.cards.four.body": "Huquqiy masalalar bo‘yicha konsultatsiya xizmatlari ko‘rsatish",
        "practice.cards.five.title": "Korxonalarni ro‘yxatdan o‘tkazish",
        "practice.cards.five.body": "Korxonalarni ro‘yxatdan o‘tkazish va ta’sis hujjatlarini tayyorlash",
        "practice.cards.six.title": "Shartnoma nizolari",
        "practice.cards.six.body": "Shartnomalar bo‘yicha nizolarni hal qilish, sud jarayonlarida huquqiy hamrohlikni ta’minlash",
        "practice.cards.seven.title": "Sudlarda himoya",
        "practice.cards.seven.body": "Fuqarolik, iqtisodiy, mehnat va ma’muriy ishlar bo‘yicha fuqarolar huquqlarini sudlarda himoya qilish",
        "practice.cards.eight.title": "Chet el fuqarolari bo‘yicha xizmatlar",
        "practice.cards.eight.body": "Chet el fuqarolarining O‘zbekistondagi huquqlarini himoya qilish hamda O‘zbekistonga kirish ruxsatnomasini olishda yuridik xizmatlar ko‘rsatish",
        "trusted.title": "Yetakchi xalqaro reytinglar tomonidan e'tirof etilgan",
        "team.title": "Bizning jamoa",
        "team.viewProfile": "Profilni ko'rish",
        "team.roles.one": "Bosh hamkor",
        "team.roles.two": "Hamkor, korporativ huquq",
        "team.roles.three": "Hamkor, sud ishlari",
        "team.roles.four": "Soliq amaliyoti rahbari",
        "cta.eyebrow": "Ishingizni muhokama qilaylik",
        "cta.title": "Manfaatlaringizni himoya qilishga tayyormisiz?",
        "cta.body": "Mutaxassislarimiz bilan maxfiy maslahatga yoziling. 24 soat ichida javob beramiz.",
        "cta.contact.office": "Ofis",
      "cta.contact.address":
        "Toshkent shahri, Yunusobod tumani Minor MFY.Markaz-6 mavzesi, 111-uy, 25-xona",
      "cta.contact.phone": "Telefon",
      "cta.contact.phoneValue": "+998 88 488 0203",
      "cta.contact.phoneValue2": "+998 90 719 22 23",
      "cta.contact.email": "Email",
      "cta.contact.emailValue": "info@allegal.uz",
      "cta.contact.telegram": "Telegram",
      "cta.contact.telegramValue": "@umarjon_jumaniyazov",
      "cta.contact.instagram": "Instagram",
      "cta.contact.instagramValue": "instagram.com/all_legal.uz",
      "cta.contact.hours": "Ish vaqti",
      "cta.contact.hours.mon": "Dushanba: 9:00–18:00",
      "cta.contact.hours.tue": "Seshanba: 9:00–18:00",
      "cta.contact.hours.wed": "Chorshanba: 9:00–18:00",
      "cta.contact.hours.thu": "Payshanba: 9:00–18:00",
      "cta.contact.hours.fri": "Juma: 9:00–18:00",
      "cta.contact.hours.sat": "Shanba: yopiq",
      "cta.contact.hours.sun": "Yakshanba: yopiq",
        "form.name": "Ism",
        "form.name.placeholder": "To'liq ism",
        "form.phone": "Telefon",
        "form.phone.placeholder": "+998",
        "form.email": "Email",
        "form.email.placeholder": "example@company.com",
        "form.message": "Xabar",
        "form.message.placeholder": "Yuridik masalangizni qisqacha tasvirlab bering...",
        "form.submit": "So'rov yuborish",
        "footer.blurb": "All-Legal O'zbekiston va Markaziy Osiyodagi zamonaviy bizneslar uchun yuqori darajadagi yuridik xizmatlarni taqdim etadi.",
        "footer.firm.title": "Firma",
        "footer.firm.about": "Biz haqimizda",
        "footer.firm.team": "Jamoamiz",
        "footer.firm.practice": "Xizmat yo'nalishlari",
        "footer.firm.contact": "Aloqa",
        "footer.firm.email": "Email",
        "footer.firm.phone": "Telefon",
        "footer.firm.instagram": "Instagram",
        "footer.firm.telegram": "Telegram",
        "footer.services.title": "Xizmatlar",
        "footer.services.corporate": "Korporativ huquq",
        "footer.services.litigation": "Sud ishlari",
        "footer.services.realestate": "Ko'chmas mulk",
        "footer.services.tax": "Soliq huquqi",
        "footer.connect.title": "Bog'lanish",
        "footer.copyright": "© 2026 All-Legal yuridik firmasi. Barcha huquqlar himoyalangan.",
        "footer.legal.privacy": "Maxfiylik siyosati",
        "footer.legal.terms": "Foydalanish shartlari"
    },
    ja: {
        "nav.practice": "業務分野",
        "nav.team": "チーム",
        "nav.about": "当事務所について",
        "nav.contact": "お問い合わせ",
        "nav.consult": "相談",
        "hero.badge": "信頼できる法律パートナー",
        "hero.title": "ウズベキスタンの<br/><span class=\"hero-accent text-accent\">リーディング・リーガルソリューション</span>",
        "hero.body": "複雑な企業法務、知的財産、訴訟案件に精通した専門的アドバイス。法務を私たちが担い、あなたは成長に集中できます。",
        "hero.cta.primary": "相談を依頼する",
        "hero.cta.secondary": "業務分野を見る",
        "why.title": "All-Legalが選ばれる理由",
        "why.body": "地域の専門知識と国際基準を組み合わせ、卓越した成果を提供します。",
        "why.cards.one.title": "豊富な経験",
        "why.cards.one.body": "地域規制と国際法の両面で20年以上の経験を蓄積しています。",
        "why.cards.two.title": "揺るぎない信頼",
        "why.cards.two.body": "中央アジアで事業を行うFortune 500企業から一貫性と倫理基準で信頼されています。",
        "why.cards.three.title": "個別アプローチ",
        "why.cards.three.body": "テンプレートは使いません。戦略はお客様の事業目標に合わせて設計します。",
        "about.established": "2022年設立",
        "about.tagline": "ウズベキスタン法での卓越性",
        "about.eyebrow": "事務所について",
        "about.title": "ウズベキスタンであなたの権利と利益を守ります",
        "about.p1": "2022年設立のAll-Legalは、ウズベキスタン共和国において法人および個人の法的権利の保護に特化しています。急速に変化する法環境の中で、明確で実行可能な助言を提供します。",
        "about.p2": "当事務所は外国投資の重要な橋渡しとして、<span class=\"text-navy dark:text-white font-semibold\">企業法務、税務計画、契約交渉、移民関連</span>の包括的支援を提供します。ライセンス取得、ビザ、就労許可の複雑な手続きを専門的に管理し、国際クライアントの円滑な運営を確保します。",
        "about.p3": "当事務所の<span class=\"text-navy dark:text-white font-semibold\">有資格弁護士7名</span>が各案件に深い知見を提供します。建設、観光、貿易、IT、金融などの主要分野で、<span class=\"text-navy dark:text-white font-semibold\">70以上の法人</span>の支援実績を誇ります。",
        "about.stats.entities": "支援実績の法人",
        "about.stats.sectors": "主要分野",
        "about.stats.lawyers": "有資格弁護士",
        "practice.eyebrow": "専門分野",
        "practice.title": "業務分野",
        "practice.viewAll": "すべての分野を見る",
        "practice.learnMore": "詳しく見る",
        "practice.cards.one.title": "契約書の作成・レビュー",
        "practice.cards.one.body": "契約書の作成、分析、法的レビューを実施します。",
        "practice.cards.two.title": "雇用関連書類",
        "practice.cards.two.body": "雇用契約および労働関連の各種規程を作成します。",
        "practice.cards.three.title": "労働法の助言",
        "practice.cards.three.body": "労働法に関する法的助言を提供します。",
        "practice.cards.four.title": "法務コンサルティング",
        "practice.cards.four.body": "法務に関するコンサルティングサービスを提供します。",
        "practice.cards.five.title": "会社設立・登録",
        "practice.cards.five.body": "会社設立の登録および定款等の作成を行います。",
        "practice.cards.six.title": "契約紛争の解決",
        "practice.cards.six.body": "契約紛争の解決と裁判手続における法的支援を提供します。",
        "practice.cards.seven.title": "裁判での代理",
        "practice.cards.seven.body": "民事・経済・労働・行政事件における権利保護を行います。",
        "practice.cards.eight.title": "外国籍の方の支援",
        "practice.cards.eight.body": "ウズベキスタンでの外国籍の方の権利保護と入国許可取得の法的支援を提供します。",
        "trusted.title": "主要な国際ディレクトリで認知",
        "team.title": "チーム",
        "team.viewProfile": "プロフィールを見る",
        "team.roles.one": "マネージング・パートナー",
        "team.roles.two": "パートナー（企業法務）",
        "team.roles.three": "パートナー（訴訟）",
        "team.roles.four": "税務部門責任者",
        "cta.eyebrow": "案件のご相談",
        "cta.title": "利益を守る準備はできていますか？",
        "cta.body": "機密性の高い相談を予約してください。24時間以内にご連絡します。",
        "cta.contact.office": "オフィス",
        "cta.contact.address": "Toshkent shahri, Yunusobod tumani Minor MFY.Markaz-6 mavzesi, 111-uy, 25-xona",
      "cta.contact.phone": "電話",
      "cta.contact.phoneValue": "+998 88 488 0203",
      "cta.contact.phoneValue2": "+998 90 719 22 23",
      "cta.contact.email": "メール",
      "cta.contact.emailValue": "info@allegal.uz",
      "cta.contact.telegram": "Telegram",
      "cta.contact.telegramValue": "@umarjon_jumaniyazov",
      "cta.contact.instagram": "Instagram",
      "cta.contact.instagramValue": "instagram.com/all_legal.uz",
      "cta.contact.hours": "営業時間",
      "cta.contact.hours.mon": "月: 9:00–18:00",
      "cta.contact.hours.tue": "火: 9:00–18:00",
      "cta.contact.hours.wed": "水: 9:00–18:00",
      "cta.contact.hours.thu": "木: 9:00–18:00",
      "cta.contact.hours.fri": "金: 9:00–18:00",
      "cta.contact.hours.sat": "土: 休業",
      "cta.contact.hours.sun": "日: 休業",
        "form.name": "氏名",
        "form.name.placeholder": "氏名（フルネーム）",
        "form.phone": "電話番号",
        "form.phone.placeholder": "+998",
        "form.email": "メール",
        "form.email.placeholder": "example@company.com",
        "form.message": "お問い合わせ内容",
        "form.message.placeholder": "ご相談内容を簡単にご記入ください…",
        "form.submit": "送信する",
        "footer.blurb": "All-Legalはウズベキスタンおよび中央アジアの現代企業の複雑なニーズに合わせた高品質な法務サービスを提供します。",
        "footer.firm.title": "事務所",
        "footer.firm.about": "私たちについて",
        "footer.firm.team": "チーム",
        "footer.firm.practice": "業務分野",
        "footer.firm.contact": "お問い合わせ",
        "footer.firm.email": "メール",
        "footer.firm.phone": "電話",
        "footer.firm.instagram": "Instagram",
        "footer.firm.telegram": "Telegram",
        "footer.services.title": "サービス",
        "footer.services.corporate": "企業法務",
        "footer.services.litigation": "訴訟",
        "footer.services.realestate": "不動産",
        "footer.services.tax": "税務",
        "footer.connect.title": "つながる",
        "footer.copyright": "© 2026 All-Legal法律事務所。無断転載を禁じます。",
        "footer.legal.privacy": "プライバシーポリシー",
        "footer.legal.terms": "利用規約"
    }
};

const supportedLangs = ["en", "ru", "uz", "ja"];

const setActiveLangButton = (lang) => {
    document.querySelectorAll("[data-lang]").forEach((button) => {
        if (button.getAttribute("data-lang") === lang) {
            button.className = "px-3 py-1 text-xs font-bold rounded bg-white dark:bg-gray-700 text-primary shadow-sm";
        } else {
            button.className = "px-3 py-1 text-xs font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900";
        }
    });
};

const applyTranslations = (lang) => {
    const dict = translations[lang] || translations.en;
    document.documentElement.lang = lang;

    document.querySelectorAll("[data-i18n]").forEach((el) => {
        const key = el.getAttribute("data-i18n");
        if (dict[key]) {
            el.textContent = dict[key];
        }
    });

    document.querySelectorAll("[data-i18n-html]").forEach((el) => {
        const key = el.getAttribute("data-i18n-html");
        if (dict[key]) {
            el.innerHTML = dict[key];
        }
    });

    document.querySelectorAll("[data-i18n-attr]").forEach((el) => {
        const key = el.getAttribute("data-i18n");
        const attr = el.getAttribute("data-i18n-attr");
        if (dict[key] && attr) {
            el.setAttribute(attr, dict[key]);
        }
    });

    setActiveLangButton(lang);
    localStorage.setItem("lang", lang);
};

document.querySelectorAll("[data-lang]").forEach((button) => {
    button.addEventListener("click", () => {
        const lang = button.getAttribute("data-lang");
        if (supportedLangs.includes(lang)) {
            applyTranslations(lang);
        }
    });
});

const practicePanel = document.querySelector(".practice-extra");
const practiceToggles = document.querySelectorAll('[data-action="practice-toggle"]');
const setPracticeExpanded = (expanded) => {
    if (!practicePanel) {
        return;
    }
    practicePanel.classList.toggle("is-open", expanded);
    practicePanel.setAttribute("data-state", expanded ? "expanded" : "collapsed");
    practiceToggles.forEach((btn) => btn.setAttribute("aria-expanded", expanded));
};

practiceToggles.forEach((btn) => {
    btn.addEventListener("click", () => {
        const expanded = practicePanel?.classList.contains("is-open");
        setPracticeExpanded(!expanded);
    });
});

const savedLang = localStorage.getItem("lang");
const initialLang = supportedLangs.includes(savedLang) ? savedLang : "en";
applyTranslations(initialLang);
